var questions = [
  "What's something you know about yourself that you have a hard time believing?",
  "What was your favorite song to sing as a child?",
  "What was your favorite game to play as a child?",
  "Do you prefer to stay indoors or go outside when it's raining?",
  "When was the last time you sang out loud, either to yourself or someone else? What did you sing?",
  "If you knew that you were going to die in six months, what would you change about your life?",
  "How do you feel about your relationship with your mother?",
  "Notice the people around you. What is something you'd like to say as a compliment to one of them right now?",
  "What's been the highlight of your day so far?",
  "Which feeling do you strive to feel the most of every day?",
  "If you have pets, do you cook for them? What is their favorite food?",
  "Where is the most unusual place you've slept?",
  "What was the name of your last pet and what inspired their name?",
  "What was your favorite meal as a 10-year old child, who made it, and do you still eat it today?",
  "When do you feel the most at peace?",
  "What’s the most recent act of kindness you performed for a stranger?",
  "What makes you feel incredibly happy?",
  "What's your favorite sweet treat? If you had only one of these left, who would you share it with?",
  "Boots, sandals, stilettos, climbing shoes, cleats, ice skates, snow shoes, ballet slippers, bowling shoes or barefoot?",
  "If you had to get rid of all of your material possessions except one, what would you keep and why?",
  "What are some of your nicknames?",
  "If you were sitting on an 8-hour flight, who would you want to sit next to and why?",
  "Do you have any scars on your body? If yes, how did you get them?",
  "If you could keep a VERY large animal as a pet, which would you choose?",
  "Do you remember the telephone number of your first childhood home?",
  "If there were no financial or geographical limitations, what would your dream wedding look like?",
  "If the only shirt available to wear all day today was 2 sizes too small, or 2 sizes too big, which would you choose?",
  "Do you believe in extra-terrestrials? Why or why not?",
  "What are your three favorite outdoor activities?",
  "Have you done anything while traveling that you wouldn't do in your home country?",
  "Where in the world would you like to be stuck?",
  "What's your happiest childhood memory?",
  "If you were given a FREE one-way plane ticket to anywhere in the world, and you had to leave in one hour, where would you go?",
  "What's your definition of a soulmate and do you have one?",
  "Which three words describe your ideal best friend?",
  "What's the lesson that keeps repeating in your life right now?",
  "Which of your own body parts is your favorite?",
  "Where were you born?",
  "Which countries have you traveled to?",
  "Which countries have you lived in for more than one month?",
  "Who have you lost touch with that you would like to reconnect with?",
  "What's your favorite memory with your Mom?",
  "If you found $100 cash on the ground today, what would you do with it?",
  "If you found $1,000 cash on the ground today, what would you do with it?",
  "If a crystal ball could tell you the truth about anything in your future, what would you want to know?",
  "When is the last time you laughed really really hard? What happened and who were you with?",
  "What's the next destination on your travel list and why?",
  "If you could have any one super-power, which would you choose and why?",
  "What's one item on your Life Goals list, and when do you plan to do it?",
  "Which languages do you fluently speak, read or write?",
  "Do you have any tattoos? If yes, what was the inspiration for your most recent one? If no, what would you consider tattooing on your skin?",
  "What was a recent unexpected act of kindness you received from a stranger, and how did it make you feel?",
  "If you had to take off one piece of clothing right now and give it away forever, what would you choose and why?",
  "What was the most recent home-cooked meal you made for someone, and who did you make it for?",
  "What do you think is the most important skill to have in relationships?",
  "What's one thing you want to be remembered for?",
  "What was one of your most passionate hobbies as a child and do you still do that today?",
  "Describe a time when something synchronistic and magical happened?",
  "What's an unusual dream you've had while sleeping and still remember?",
  "What's one thing you tried, and will never do again?",
  "What styles of dance do you know or have you tried?",
  "Do you have a good babysitter story?",
  "How old were you the last time you went trick-or-treating?",
  "Do you know how to ice skate, ski or snowboard?",
  "If you could order a smoothie right now, what flavor would you want?",
  "What poem or song did you memorize as a child that you still remember today?",
  "How many hats do you own?",
  "Who is the person or couple in your life that taught you the most about healthy relationships?",
  "If you didn't know your biological age, how old would you say you feel?",
  "What's the most romantic thing someone has ever done for you?",
  "Who was your first kiss with? How old were you and where did it happen?",
  "If you could instantly acquire 10 pounds of any one thing, what would you choose?",
  "If you could teleport anywhere right now, where would you go?",
  "Where did you go on your last trip?",
  "What was the last great find you bought at a thrift store, and how much did you pay for it?",
  "When was the last time you took a cross country road trip, and what did you learn?",
  "When was the last time you hitchhiked or picked up a hitchhiker?",
  "What's something you're very proud of accomplishing so far in your life?",
  "What do you wear to bed?",
  "Who is the person you think of most often during the day, and why?",
  "Can you come up with a secret handshake right now and demonstrate it?",
  "When was the last time you planted seeds or had a garden? What did you grow?",
  "What did you eat for breakfast today?",
  "What's your first thought after waking up in the morning?",
  "If you didn't have to work for the next 30 days, what would you do instead?",
  "What's the most fantastical thing you can imagine doing in your lifetime? Will you do it?",
  "If you could change any one thing about your life right now, what would it be?",
  "What's the best decision you've ever made?",
  "If you could go back in time and do one thing differently in your life, what would you do and why?",
  "If you knew you'd be paid generously to do what you're most passionate about, what would you be doing right now?",
  "Would you like to be famous?",
  "How would you design your own 'perfect day'?",
  "If you could change something about your childhood or the way you were raised, what would you change?",
  "What's something you've been dreaming of doing?",
  "When was the last time you cried?",
  "If you could call your younger self 10 years ago, and had 30 seconds to speak, what would you say?",
  "What mistake have you made more than once?",
  "How old were you when you got your first job, and what did you do?",
  "What's your favorite flavor of pie?",
  "What's the weirdest thing you've ever eaten?",
  "What are five things you love to do every day?",
  "What skill or knowledge do you wish you had learned as a child?",
  "What makes you feel like you are 'at home'?",
  "What's a gift you've received that you really cherish?",
  "What are you really good at?",
  "If you're in a relationship, how did you meet your current partner? If you're single, what's one of your favorite 'how we met' stories?",
  "Tell me about an amazing meal that you had. Who were you with?",
  "If you only had one choice, which would you choose: a) to leave your current country, but never be allowed to return or b) to continue living in your current country but never be allowed to leave",
  "What's your dream vacation?",
  "If you had to chose a partner based only on the types of shoes they have in their closet, which three styles of shoes would you be looking for?",
  "If you could only do one of these things with your partner and not the other, would you choose to hold hands or kiss?",
  "What possession do you no longer have that you would love to get back? (Could be something you lost, sold, broke, gave away or was stolen).",
  "What would you still like to learn in this lifetime?",
  "When was the last time you surprised someone and how?",
  "When was the last time you went skinny dipping, and where were you?",
  "What are you really good at cooking?",
  "What's your favorite personal motto or mantra?",
  "Who is your favorite teacher and why?",
  "Who were the last three people you said 'I love you' to?",
  "What do you collect currently or have you collected in the past?",
  "What's the biggest lesson you learned from your last relationship?",
  "Do you prefer to travel alone – or with a partner, family member or friend?",
  "When you travel, do you prefer to camp, couchsurf, stay in hostels, bed and breakfasts, hotels or all-inclusive resorts?",
  "What's your favorite book to recommend?",
  "Would you consider adopting a child?",
  "What do you do on a typical Friday night?",
  "How many times have you gone camping in the past year?",
  "What was the last BIG risk you took?",
  "Do you care if the food you eat is organically grown?",
  "What are the last three things you taught yourself to do?",
  "Which musical instruments do you play?",
  "Have you ever written a song or poem for somebody?",
  "What percentage of your meals do you prepare yourself at home compared to restaurant food?",
  "When was the last time you raised your voice during a conversation and why?",
  "How many vehicle accidents have you been in during your lifetime?",
  "What are your top priority goals in life right now? (in the next 3-6 months)",
  "Do you know how to change the oil on your car?",
  "Do you know how to change a flat tire?",
  "What is the last thing you built with your own hands?",
  "When you're invited to a potluck dinner party, what do you usually bring?",
  "Name one activity that you do on a regular basis that lights you up and brings a smile to your face?",
  "Have you ever moved to another city, state or country to be with a romantic partner?",
  "What's your favorite scent?",
  "Which scent do you really dislike?",
  "What habit would you like to break?",
  "Whats the first thing you do when you get home from a trip?",
  "If you could do something dangerous just once, with absolutely no risk of getting hurt, what would you do?",
  "What are three things you always carry in your purse or wallet?",
  "Do you know why your parents chose your birth name?",
  "When was the last time you got pulled over for speeding?",
  "What's the most creative story you've told to get out of a speeding or parking ticket?",
  "What would you want to be considered an expert in?",
  "If you could rename yourself, what name would you choose?",
  "What's the most fun you've ever had at a party?",
  "Have you ever had an experience that led you to believe in angels or spirit guides?",
  "What is the oldest item in your closet and why do you still have it?",
  "Name three of your most unique skills?",
  "What is your favorite meal to prepare and eat?",
  "What's something you do, or used to do, that most people wouldn't guess just by looking at you?",
  "What was your favorite childhood toy?",
  "What was the first musical record album, cassette tape, CD or digital audio file you ever purchased?",
  "What do you wish you knew more about?",
  "What's an experience you've had that convinced you that there are phenomena in this world that cannot be explained by science alone?",
  "What's something you recently learned that completely surprised you?",
  "What's something that you were extremely nervous to try, but did anyway?",
  "What would your parents be surprised to learn about you?",
  "Who knows you the best?",
  "Which 'after school activities' did you do during your teen years?",
  "What’s been your favorite age to be so far?",
  "If you could have been a child prodigy, what would you want to be skilled at?",
  "Which celebrity would you want to trade lives with?",
  "What story do your friends still tease you about?",
  "What's something a date could do or say that would be a complete turn-off and dealbreaker for moving forward with a potential relationship?",
  "If your budget was unlimited, and you could choose one person to receive a gift, what present would you get and who would you give it to?",
  "Do you have a lucky charm, mantra, or tradition you use or say to yourself when you are nervous?",
  "What's your favorite type of tree?",
  "How often do you read your horoscope?",
  "Have you ever milked a cow or a goat?",
  "Have you ever been whale watching?",
  "Have you ever been fly fishing?",
  "Have you killed an animal for sport or food?",
  "Have you ever made your own ice cream?",
  "What was the last theatrical play, musical or opera you saw?",
  "Have you ever slept in a teepee?",
  "How often do you write in a journal?",
  "Have you ever been detained at an international border crossing or airport? What happened?",
  "What does your favorite coffee, tea or cocoa mug look and feel like?",
  "Do you want to donate your organs?",
  "Are you good at giving massages?",
  "What is something you've failed at?",
  "Have you ever walked on a tightrope or a slack line?",
  "Have you ever ridden a unicycle?",
  "Do you give cash to talented musicians who play on the street?",
  "Have you ever been on public radio or TV, or in a film or video?",
  "Have you ever been in a musical performance, an actor in a play or performed on stage for any reason?",
  "Which sports have you played?",
  "Have you ever received stitches for an injury?",
  "What was the last totally inappropriate thing you said in public?",
  "Have you ever been in a submarine?",
  "Who was your first romantic crush on?",
  "Are you afraid of needles?",
  "Do you know any magic tricks?",
  "Would you be comfortable changing out of your current clothing and into a new outfit while inside of a parked car?",
  "If you could only have one piece of furniture in your house, what would you choose?",
  "Have you ever planted a tree?",
  "What was the last design you carved into a pumpkin?",
  "Have you ever accidentally swallowed a non-edible object? What was it and what happened?",
  "Do you have a written Bucket List of things you want to do or places you want to see before you die?",
  "Have you ever stolen anything?",
  "Who is the smartest person you know?",
  "Would you let your parents pick out a romantic partner for you?",
  "Have you ever eaten canned SPAM?",
  "Which casino or card game are you the best at?",
  "What topic has been on your mind the most lately?",
  "What is your personal passion project right now?",
  "What’s one of the most uncomfortable situations you’ve ever been in?",
  "What's something that made you feel happy today?",
  "What's something that made you feel sad today?",
  "Has anyone in your family served in the military? If yes, what have they shared with you about their experience.",
  "Did your parents have any cute nicknames for each other?",
  "Which of the four seasons is your favorite?",
  "What is the last great book you read and what did you most like about it?",
  "How did you celebrate your last birthday?",
  "Do you know how and where your parents met and how old they were at the time?",
  "If you had one hour of uninterrupted privacy right now, what would you like to do?",
  "What's the most interesting thing your grandparents taught you?",
  "What do you do when you find a spider in your house?",
  "Do you have a favorite breed of dog?",
  "What's your favorite flavor of ice cream?",
  "What is the most expensive thing you've ever purchased?",
  "What's the next big purchase you're planning to make?",
  "What is your favorite breakfast meal?",
  "Which natural talents do you believe you were born with?",
  "If you could take a week-long bike tour of any place or country, where would you go?",
  "If you weren't worried about what anyone else would think of you, what would you love to do spontaneously right now?",
  "How long does it take you to fall asleep?",
  "How do you like to eat eggs?",
  "Do you have a favorite childhood book?",
  "How do you feel when you see an older couple holding hands?",
  "What's the last green thing you ate?",
  "What makes you feel the most at peace?",
  "Have you ever had a memorable conversation with a stranger in an elevator?",
  "What's the longest walk or hike you've ever completed?",
  "Have you ever stayed in a relationship past its 'expiration date'? If yes, why didn't you end it sooner?",
  "Which beverage would you love to drink every day?",
  "Which family recipe have you learned how to make?",
  "Which three qualities or characteristics do you look for in new friends?",
  "Would you describe yourself as a physically flexible person?",
  "Do you feel more energized when you are alone or when you are around others?",
  "Have you ever been scuba diving or snorkeling?",
  "What is the most amount of money you've found and what did you do with it?",
  "Have you ever punched anyone in the face?",
  "What's something that other people do that really bothers you?",
  "How would you describe your favorite pair of socks?",
  "What's your favorite sandwich?",
  "What's the best advice you've ever received?",
  "Have you ever dreamed of living in a different era?",
  "What is the most interesting question you've been asked recently?",
  "Do you need to 'see it to believe it' or 'believe it to see it'?",
  "How many keys are on your keychain and what are each of the keys for?",
  "When was the last time you felt lonely?",
  "What's something you're really really great at?",
  "What's the most significant change you've made in the past six months?",
  "What are you avoiding right now?",
  "What's the most exciting way you've been greeted by a stranger?",
  "Do you have an animal totem, or notice a specific animal repeatedly appearing during significant times in your life?",
  "Which feeling are you most craving to feel right now?",
  "Is there something you've already committed to doing that you really don't want to do?",
  "What are you waiting for in your life right now?",
  "What do you want right now more than anything else?",
  "When was the time you said something you really regretted afterward?",
  "What's something you need help with right now in your life?",
  "Where was the most exotic or unusual place you've ever made love?",
  "When was your last intensely-passionate kiss and who was it with?",
  "Have you ever peed or pooped in your pants as an adult? What happened?",
  "How old were you when you met your last great love?",
  "What is the greatest pain you have ever felt?",
  "Notice the people around you. What is something you'd like to say as a compliment to one of them right now?",
  "What's been the highlight of your day so far?",
  "Which feeling do you strive to feel the most of every day?",
  "If you have pets, do you cook for them? What is their favorite food?",
  "Where is the most unusual place you've slept?",
  "What was the name of your last pet and what inspired their name?",
  "What was your favorite meal as a 10-year old child, who made it, and do you still eat it today?",
  "When do you feel the most at peace?",
  "What’s the most recent act of kindness you performed for a stranger?",
  "What makes you feel incredibly happy?",
  "What's your favorite sweet treat? If you had only one of these left, who would you share it with?",
  "Boots, sandals, stilettos, climbing shoes, cleats, ice skates, snow shoes, ballet slippers, bowling shoes or barefoot?",
  "If you had to get rid of all of your material possessions except one, what would you keep and why?",
  "What are some of your nicknames?",
  "If you were sitting on an 8-hour flight, who would you want to sit next to and why?",
  "Do you have any scars on your body? If yes, how did you get them?",
  "If you could keep a VERY large animal as a pet, which would you choose?",
  "Do you remember the telephone number of your first childhood home?",
  "If there were no financial or geographical limitations, what would your dream wedding look like?",
  "If the only shirt available to wear all day today was 2 sizes too small, or 2 sizes too big, which would you choose?",
  "Do you believe in extra-terrestrials? Why or why not?",
  "What are your three favorite outdoor activities?",
  "Have you done anything while traveling that you wouldn't do in your home country?",
  "Where in the world would you like to be stuck?"
]
if (Questions.find().count() === 0) {
  questions.forEach(function(question){
    Questions.insert({
      question: question,
      isAdult: false
    });
  });
}

